include:
  - project: 'templates/ci/infogene-standard-code-scans'
    ref: main
    file: 'standard-scans.gitlab-ci.yml'

variables:
  JOB_DAST_ENABLED: 0
  JOB_CTSN_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

# CUSTOM JOBS
docker-build:
  # Use the official docker image.
  image: docker:cli
  stage: build
  services:
    - docker:dind
  variables:
    PHP_VERSION: 8.4
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    GHCR_IMAGE: ghcr.io/infogene/nginx-php
  before_script:
    - echo -n $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  # All branches are tagged with $DOCKER_IMAGE_NAME (defaults to commit ref slug)
  # Default branch is also tagged with `latest`
  script:
    - docker build --pull --build-arg "PHP_VERSION=$PHP_VERSION" -f Dockerfile.alpine -t "$DOCKER_IMAGE_NAME-alpine" .
    - docker build --pull --build-arg "PHP_VERSION=$PHP_VERSION" -f Dockerfile.debian -t "$DOCKER_IMAGE_NAME-debian" .
    - docker tag "$DOCKER_IMAGE_NAME-alpine" "$DOCKER_IMAGE_NAME"
    - docker push "$DOCKER_IMAGE_NAME-alpine"
    - docker push "$DOCKER_IMAGE_NAME-debian"
    - docker push "$DOCKER_IMAGE_NAME"
    - |
      if [[ ! -z "$CI_COMMIT_TAG" ]]; then
        docker tag "$DOCKER_IMAGE_NAME-alpine" "$CI_REGISTRY_IMAGE:$PHP_VERSION-alpine-$CI_COMMIT_TAG"
        docker tag "$DOCKER_IMAGE_NAME-debian" "$CI_REGISTRY_IMAGE:$PHP_VERSION-debian-$CI_COMMIT_TAG"
        docker tag "$DOCKER_IMAGE_NAME-alpine" "$CI_REGISTRY_IMAGE:$PHP_VERSION-alpine"
        docker tag "$DOCKER_IMAGE_NAME-debian" "$CI_REGISTRY_IMAGE:$PHP_VERSION-debian"
        docker tag "$DOCKER_IMAGE_NAME-alpine" "$CI_REGISTRY_IMAGE:$PHP_VERSION"
        docker tag "$DOCKER_IMAGE_NAME-alpine" "$CI_REGISTRY_IMAGE:latest"
        docker push "$CI_REGISTRY_IMAGE:$PHP_VERSION-alpine-$CI_COMMIT_TAG"
        docker push "$CI_REGISTRY_IMAGE:$PHP_VERSION-debian-$CI_COMMIT_TAG"
        docker push "$CI_REGISTRY_IMAGE:$PHP_VERSION-alpine"
        docker push "$CI_REGISTRY_IMAGE:$PHP_VERSION-debian"
        docker push "$CI_REGISTRY_IMAGE:$PHP_VERSION"
        docker push "$CI_REGISTRY_IMAGE:latest"
      
        # PUSH TO Github Container Registry
        echo -n $CI_GHCR_TOKEN | docker login -u $CI_GHCR_USER --password-stdin ghcr.io
      
        docker tag "$DOCKER_IMAGE_NAME-alpine" "$GHCR_IMAGE:$PHP_VERSION-alpine-$CI_COMMIT_TAG"
        docker tag "$DOCKER_IMAGE_NAME-debian" "$GHCR_IMAGE:$PHP_VERSION-debian-$CI_COMMIT_TAG"
        docker tag "$DOCKER_IMAGE_NAME-alpine" "$GHCR_IMAGE:$PHP_VERSION-alpine"
        docker tag "$DOCKER_IMAGE_NAME-debian" "$GHCR_IMAGE:$PHP_VERSION-debian"
        docker tag "$DOCKER_IMAGE_NAME-alpine" "$GHCR_IMAGE:$PHP_VERSION"
        docker tag "$DOCKER_IMAGE_NAME-alpine" "$GHCR_IMAGE:latest"
        docker push "$GHCR_IMAGE:$PHP_VERSION-alpine-$CI_COMMIT_TAG"
        docker push "$GHCR_IMAGE:$PHP_VERSION-debian-$CI_COMMIT_TAG"
        docker push "$GHCR_IMAGE:$PHP_VERSION-alpine"
        docker push "$GHCR_IMAGE:$PHP_VERSION-debian"
        docker push "$GHCR_IMAGE:$PHP_VERSION"
        docker push "$GHCR_IMAGE:latest"
      fi
  # Run this job in a branch where a Dockerfile exists
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG
